sudo: required
services:
  - docker

after_success:
  - docker build -t koyasu221b/multi-client ./client
  - docker build -t koyasu221b/multi-nginx ./nginx
  - docker build -t koyasu221b/multi-server ./server
  - docker build -t koyasu221b/multi-worker ./worker

  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin


  # Take those images and push them to docker hub
  - docker push koyasu221b/multi-client
  - docker push koyasu221b/multi-nginx
  - docker push koyasu221b/multi-server
  - docker push koyasu221b/multi-worker
