sudo: required
services:
  - docker

before_install:
  - gem install bundler

after_success:
  - docker build -t koyasu221b/multi-client ./client
  - docker build -t koyasu221b/multi-nginx ./nginx
  - docker build -t koyasu221b/multi-server ./server
  - docker build -t koyasu221b/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push koyasu221b/multi-client
  - docker push koyasu221b/multi-nginx
  - docker push koyasu221b/multi-server
  - docker push koyasu221b/multi-worker
